### ISSUE TITLE
Preloading error when piping/mounting the vpy script

### ISSUE THREAD

**Issue by banjaminicc** [AmusementClub/vs-mlrt#13]
```
vstrt: failed to preload C:\Users\\AppData\Roaming\VapourSynth\plugins64\vsmlrt-cuda\cublas64_11.dll, errno 127
```

Been getting this message after updating torch and it seems to be causing the pipe to end abruptly randomly
Any ideas?
have tried rolling back my torch version but it did not work

**Comment by AkarinVS** [comment]
errno 127 means there are DLL conflicts.

Specifically, pytorch uses its own copy of cudnn and due to poor naming of those DLLs (only major version included), there are unavoidable conflicts when you use both vs-mlrt and pytorch.

tl;dr is you can't reliably use both vs-mlrt and pytorch in the same script.

out of curiosity, which models are you running with pytorch? thanks.

**Comment by banjaminicc** [comment]
> 

Ah, I'm attempting to run a GMFUPSS model in pytorch, which again, is probably out of the support scope of this repo haha. Thanks for pointing the direction though I'd look into it!
