### ISSUE TITLE
CUGAN clamp still necessary?

### ISSUE THREAD

**Issue by ViRb3** [AmusementClub/vs-mlrt#31]
From your CUGAN wiki page https://github.com/AmusementClub/vs-mlrt/wiki/CUGAN:

```python
# clamp src to be safe as out of range values will produce large negative output.
src = core.akarin.Expr(src, "x 0 1 clamp")
```

But I noticed the following changes:
- 9d4ad4dc0ea7d3473d33e3f0e55c5d76a4c8e78a
- 13e37846b2ff207ca330c21a873f7601adae7fb7

I tried without clamp, and previously problematic footage no longer causes graphical glitches. Is this clamp still necessary? The only difference I can notice is that the clamp makes the highlights a bit darker.

Thanks!

**Comment by WolframRhodium** [comment]
Thanks, CUGAN clamp is not required now.

**Comment by ViRb3** [comment]
@WolframRhodium You may also want to remove the note:
> Make sure your RGBS input to CUGAN is within [0,1] range. Out of range values will trip the NN into producing large negative values.

**Comment by WolframRhodium** [comment]
> Thanks, CUGAN clamp is not required now.

I think I make a mistake here because that depends on the model and the video sources.

**Comment by ViRb3** [comment]
Oh, could you please explain? I have no idea what the pre-clamp or conformance expressions do.

**Comment by WolframRhodium** [comment]
It's usually a good habit to pre-clamp the input when using any ML model, otherwise the output may contains out-of-range pixels.

The `conformance` flag is given because the original PyTorch implementation inferences in a scaled range but this behavior was not included in previous versions of vs-mlrt, and we want to allow users expecting the old behavior can switch easily.
