### ISSUE TITLE
Directly take in onnx as fp16 and perform inference without quantization

### ISSUE THREAD

**Issue by banjaminicc** [AmusementClub/vs-mlrt#84]
Is it possible to not re-quantize the model with fp16 is selected in vsort?
With some onnx models it seems to cause this error
```
[W:onnxruntime:, constant_folding.cc:212 onnxruntime::ConstantFolding::ApplyImpl] Could not find a CPU kernel and hence can't constant fold Sub node '/Sub_4'
```
And the produced image from inference becomes garbled
Please close directly if this is already the current implementation/There is no fix for this issue as I am not running one of the onnx/model architectures provided by vsmlrt

**Comment by banjaminicc** [comment]
On the same note
I'm confident that the onnx works with vs-ort because when setting fp16=False, inference passes with no problem.

**Comment by WolframRhodium** [comment]
All backends except vs-trt should be able to import pre-quantized onnx models, because `fp16` in these backends simply do the quantization before feeding into the underlying acceleration libraries.

Of course this does not mean they can be run on every hardware because of various issues, like the one you're encountering. It is therefore generally recommended to provide fp32 models for compatibility.

fp16 i/o, however, is only implemented in vs-trt for now, but vs-ov may probably work by doing the conversion itself.

**Comment by banjaminicc** [comment]
> All backends except vs-trt should be able to import pre-quantized onnx models, because `fp16` in these backends simply do the quantization before feeding into the underlying acceleration libraries.
> 
> Of course this does not mean they can be run on every hardware because of various issues, like the one you're encountering. It is therefore generally recommended to provide fp32 models for compatibility.
> 
> fp16 i/o, however, is only implemented in vs-trt for now, but vs-ov may probably work by doing the conversion itself.

I understand. But my model doesn't seem to be able to be re-quantized, I'm able to directly produce a fp16 quantized onnx. Is it possible to skip the re-quantize stage and directly feed it to inference?

**Comment by WolframRhodium** [comment]
By default it uses `fp16=False`, which is without re-quantization.

**Comment by banjaminicc** [comment]
But when fp16 is False does it perform inference in fp16 if I give it a fp16 quantized onnx?

**Comment by banjaminicc** [comment]
Many thanks
